/*
 * Builds src/utils/pluginDescriptionsRu.ts from a name -> Russian description JSON file.
 * Each entry stores a hash of the English description it was translated from, so a translation
 * is only shown while the English text is unchanged.
 *
 * Usage: node scripts/nightcord/genDescriptions.cjs <plugins.json from generatePluginJson> <ru.json>
 */
// @ts-check
const fs = require("fs");
const path = require("path");

const [pluginsFile, ruFile] = process.argv.slice(2);
if (!pluginsFile || !ruFile) throw new Error("Usage: genDescriptions.cjs <plugins.json> <ru.json>");

// Must match hashDescription() in src/utils/i18n.ts
function fnv1a(str) {
    let h = 0x811c9dc5;
    for (let i = 0; i < str.length; i++) {
        h ^= str.charCodeAt(i);
        h = Math.imul(h, 0x01000193);
    }
    return (h >>> 0).toString(36);
}

const plugins = JSON.parse(fs.readFileSync(pluginsFile, "utf8").replace(/^﻿/, ""));
const ru = JSON.parse(fs.readFileSync(ruFile, "utf8"));

const entries = [];
const missing = [];
for (const p of plugins.sort((a, b) => a.name.localeCompare(b.name))) {
    if (!ru[p.name]) { missing.push(p.name); continue; }
    entries.push(`    ${JSON.stringify(p.name)}: [${JSON.stringify(fnv1a(p.description))}, ${JSON.stringify(ru[p.name])}],`);
}
const unknown = Object.keys(ru).filter(n => !plugins.some(p => p.name === n));

const out = `/*
 * Vencord, a Discord client mod
 * Copyright (c) 2026 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

// Generated by scripts/nightcord/genDescriptions.cjs. Do not edit by hand.
// name: [hash of the English description, Russian description]
export const PLUGIN_DESCRIPTIONS_RU: Record<string, [string, string]> = {
${entries.join("\n")}
};
`;
const target = path.join(__dirname, "..", "..", "src", "utils", "pluginDescriptionsRu.ts");
fs.writeFileSync(target, out);
console.log(`${entries.length} translations written`);
if (missing.length) console.log("no translation:", missing.join(", "));
if (unknown.length) console.log("unknown plugins in translations:", unknown.join(", "));
