/*
 * Builds src/utils/pluginSettingsRu.ts from scripts/nightcord/data/plugin-settings.ru.json.
 *
 * Data format: { Plugin: { settingKey: [English description, Russian title, Russian description, { "English option": "Russian option" }?] } }
 * Only a hash of the English description goes into the bundle, so a translation is only shown while the
 * English text it was made from is unchanged. Option labels are matched by their English text.
 *
 * Usage: node scripts/nightcord/genSettings.cjs
 */
// @ts-check
const fs = require("fs");
const path = require("path");

// Must match hashDescription() in src/utils/i18n.ts
function fnv1a(str) {
    let h = 0x811c9dc5;
    for (let i = 0; i < str.length; i++) {
        h ^= str.charCodeAt(i);
        h = Math.imul(h, 0x01000193);
    }
    return (h >>> 0).toString(36);
}

const dataFile = path.join(__dirname, "data", "plugin-settings.ru.json");
/** @type {Record<string, Record<string, [string, string, string, Record<string, string>?]>>} */
const data = JSON.parse(fs.readFileSync(dataFile, "utf8"));

let count = 0;
const lines = [];
for (const plugin of Object.keys(data).sort((a, b) => a.localeCompare(b))) {
    lines.push(`    ${JSON.stringify(plugin)}: {`);
    for (const [key, [en, title, description, options]] of Object.entries(data[plugin])) {
        const entry = [fnv1a(en), title, description].map(s => JSON.stringify(s));
        if (options && Object.keys(options).length) {
            entry.push(`{ ${Object.entries(options).map(([from, to]) => `${JSON.stringify(from)}: ${JSON.stringify(to)}`).join(", ")} }`);
        }
        lines.push(`        ${JSON.stringify(key)}: [${entry.join(", ")}],`);
        count++;
    }
    lines.push("    },");
}

const out = `/*
 * Vencord, a Discord client mod
 * Copyright (c) 2026 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

// Generated by scripts/nightcord/genSettings.cjs. Do not edit by hand.
// plugin: { setting: [hash of the English description, Russian title, Russian description, { English option: Russian option }?] }
export const PLUGIN_SETTINGS_RU: Record<string, Record<string, [string, string, string, Record<string, string>?]>> = {
${lines.join("\n")}
};
`;
const target = path.join(__dirname, "..", "..", "src", "utils", "pluginSettingsRu.ts");
fs.writeFileSync(target, out);
console.log(`${count} settings of ${Object.keys(data).length} plugins written`);
